import bcrypt from 'bcryptjs';
import { User, CreatorProfile, PortfolioItem, Brief, Engagement } from './types.ts';

// Pre-hashed password for "Demo@12345"
// Generated using bcrypt.hashSync("Demo@12345", 10)
export const DEFAULT_PASSWORD_HASH = bcrypt.hashSync('Demo@12345', 10);

export const SEED_USERS: User[] = [
  {
    _id: 'user_brand_demo',
    name: 'Kavita Singhania',
    email: 'brand@genhire.demo',
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: 'brand',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    createdAt: '2026-01-10T10:00:00.000Z',
    updatedAt: '2026-01-10T10:00:00.000Z',
  },
  {
    _id: 'user_creator_demo',
    name: 'Aarav Mehta',
    email: 'creator@genhire.demo',
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: 'creator',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    createdAt: '2026-01-11T10:00:00.000Z',
    updatedAt: '2026-01-11T10:00:00.000Z',
  },
  {
    _id: 'user_creator_2',
    name: 'Riya Kapoor',
    email: 'riya.kapoor@example.com',
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: 'creator',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    createdAt: '2026-01-12T10:00:00.000Z',
    updatedAt: '2026-01-12T10:00:00.000Z',
  },
  {
    _id: 'user_creator_3',
    name: 'Kabir Malhotra',
    email: 'kabir.malhotra@example.com',
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: 'creator',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    createdAt: '2026-01-13T10:00:00.000Z',
    updatedAt: '2026-01-13T10:00:00.000Z',
  },
  {
    _id: 'user_creator_4',
    name: 'Ananya Sharma',
    email: 'ananya.sharma@example.com',
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: 'creator',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
    createdAt: '2026-01-14T10:00:00.000Z',
    updatedAt: '2026-01-14T10:00:00.000Z',
  },
  {
    _id: 'user_creator_5',
    name: 'Arjun Rao',
    email: 'arjun.rao@example.com',
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: 'creator',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
    createdAt: '2026-01-15T10:00:00.000Z',
    updatedAt: '2026-01-15T10:00:00.000Z',
  },
  {
    _id: 'user_creator_6',
    name: 'Meera Iyer',
    email: 'meera.iyer@example.com',
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: 'creator',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=300&auto=format&fit=crop&q=80',
    createdAt: '2026-01-16T10:00:00.000Z',
    updatedAt: '2026-01-16T10:00:00.000Z',
  },
  {
    _id: 'user_creator_7',
    name: 'Dev Khanna',
    email: 'dev.khanna@example.com',
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: 'creator',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300&auto=format&fit=crop&q=80',
    createdAt: '2026-01-17T10:00:00.000Z',
    updatedAt: '2026-01-17T10:00:00.000Z',
  },
  {
    _id: 'user_creator_8',
    name: 'Ishita Verma',
    email: 'ishita.verma@example.com',
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: 'creator',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
    createdAt: '2026-01-18T10:00:00.000Z',
    updatedAt: '2026-01-18T10:00:00.000Z',
  },
  {
    _id: 'user_creator_9',
    name: 'Aditya Nair',
    email: 'aditya.nair@example.com',
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: 'creator',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80',
    createdAt: '2026-01-19T10:00:00.000Z',
    updatedAt: '2026-01-19T10:00:00.000Z',
  },
  {
    _id: 'user_creator_10',
    name: 'Sara Bansal',
    email: 'sara.bansal@example.com',
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: 'creator',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=300&auto=format&fit=crop&q=80',
    createdAt: '2026-01-20T10:00:00.000Z',
    updatedAt: '2026-01-20T10:00:00.000Z',
  },
];

export const SEED_CREATORS: CreatorProfile[] = [
  {
    _id: 'creator_1',
    userId: 'user_creator_demo',
    name: 'Aarav Mehta',
    location: 'Mumbai, Maharashtra',
    headline: 'High-Impact AI Fashion Films & Luxury Commercials',
    bio: 'Pioneering generative luxury aesthetics for modern D2C and haute couture brands across Mumbai and Milan. I specialize in temporal coherence, high-end fabric simulations, and cinematic vertical video advertising.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    specialization: 'Fashion',
    skills: ['AI Video Generation', 'Prompt Engineering', 'Temporal Consistency', 'Color Grading', 'Sound Design'],
    tools: ['Runway Gen-3 Alpha', 'Midjourney v6', 'Flux.1 Pro', 'Kling AI', 'Magnific AI', 'DaVinci Resolve'],
    models: ['Runway Gen-3 Alpha Turbo', 'Midjourney v6.1', 'Flux Schnell', 'Kling 1.5'],
    contentTypes: ['Video Ad', 'Fashion Film', 'Product Commercial', 'Cinematic Teaser'],
    styles: ['Cinematic', 'Luxury', 'Futuristic', 'Hyper-realistic', 'Minimalist'],
    formats: ['MP4', 'ProRes', '4K Ultra HD'],
    supportedAspectRatios: ['9:16', '16:9', '1:1', '4:5'],
    commercialUseReady: true,
    workflow: [
      'Concept moodboarding & style lock with Midjourney v6 + Flux.1 Pro',
      'Camera vector sequencing & temporal stabilization in Runway Gen-3 Alpha',
      'Magnific AI 4K texture upscaling & fabric detail preservation',
      'DaVinci Resolve ACES color management & spatial audio mastering',
    ],
    rateFrom: 25000,
    rating: 4.95,
    projectsCompleted: 34,
    verification: {
      toolsVerified: true,
      toolsVerifiedNote: 'Creator submitted enterprise Runway & Midjourney tool usage logs.',
      workflowVerified: true,
      workflowVerifiedNote: 'Creator submitted 4-stage end-to-end production workflow video.',
      pastWorkVerified: true,
      pastWorkVerifiedNote: 'Verified past commercial delivery for luxury apparel agency.',
    },
    createdAt: '2026-01-11T10:00:00.000Z',
    updatedAt: '2026-01-11T10:00:00.000Z',
  },
  {
    _id: 'creator_2',
    userId: 'user_creator_2',
    name: 'Riya Kapoor',
    location: 'Bengaluru, Karnataka',
    headline: 'Next-Gen EV Commercials & Automotive AI Storytelling',
    bio: 'Bridging engineering rigor with speculative hyper-visuals. I build dynamic automotive commercials, aerodynamic airflow simulations, and future mobility campaigns for global tech and EV innovators.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    specialization: 'Automotive & Tech',
    skills: ['Automotive Video Ads', 'Fluid Motion', 'Camera Mapping', 'Sound Synthesis', 'VFX Compositing'],
    tools: ['Runway Gen-3 Alpha', 'Luma Dream Machine', 'ComfyUI', 'Kling AI', 'ElevenLabs', 'After Effects'],
    models: ['Runway Gen-3 Alpha Turbo', 'Luma Ray 2', 'Wan2.1', 'ElevenLabs Multilingual v2'],
    contentTypes: ['Video Ad', 'Product Commercial', 'Brand Film', '3D Motion'],
    styles: ['Futuristic', 'Cinematic', 'High-Octane', 'Tech-Forward'],
    formats: ['MP4', 'H.265', '4K'],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    commercialUseReady: true,
    workflow: [
      'ComfyUI custom LoRA generation for vehicle consistency',
      'Runway Gen-3 high-speed motion pass and camera dolly simulation',
      'Luma Ray 2 environmental horizon blending',
      'After Effects HUD compositing & ElevenLabs electric powertrain audio',
    ],
    rateFrom: 32000,
    rating: 4.92,
    projectsCompleted: 28,
    verification: {
      toolsVerified: true,
      toolsVerifiedNote: 'Verified enterprise ComfyUI and Runway pipeline.',
      workflowVerified: true,
      workflowVerifiedNote: 'Automotive motion timeline verified via video breakdown.',
      pastWorkVerified: true,
      pastWorkVerifiedNote: 'Past project deliverable confirmed with Bengaluru EV brand.',
    },
    createdAt: '2026-01-12T10:00:00.000Z',
    updatedAt: '2026-01-12T10:00:00.000Z',
  },
  {
    _id: 'creator_3',
    userId: 'user_creator_3',
    name: 'Kabir Malhotra',
    location: 'Delhi NCR (Gurugram)',
    headline: 'Cinematic Worldbuilding & Sci-Fi Brand Advertisements',
    bio: 'Director and generative VFX lead crafting ambitious cyberpunk landscapes, architectural marvels, and theatrical brand anthems for forward-thinking consumer enterprises.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    specialization: 'Cinematic VFX',
    skills: ['Generative Sci-Fi', 'Environment Design', 'Camera Choreography', 'VFX Integration', 'Cinematography'],
    tools: ['Midjourney v6', 'Runway Gen-3 Alpha', 'Flux.1 Pro', 'Haiper AI', 'Premiere Pro'],
    models: ['Midjourney v6.1', 'Runway Gen-3 Alpha Turbo', 'Flux Schnell'],
    contentTypes: ['Brand Film', 'Cinematic Teaser', 'Video Ad', 'Sci-Fi Short'],
    styles: ['Cinematic', 'Futuristic', 'Dystopian/Utopian', 'Atmospheric', 'Epic'],
    formats: ['MP4', 'ProRes 422', '1080p', '4K'],
    supportedAspectRatios: ['16:9', '9:16', '2.39:1'],
    commercialUseReady: true,
    workflow: [
      'Prompt engineering with Claude 3.5 Sonnet for rich world lore',
      'Midjourney base plate & keyframe art direction',
      'Runway Gen-3 Alpha cinematic multi-axis tracking shot generation',
      'Premiere Pro editing, Foley sound layering & grain emulation',
    ],
    rateFrom: 28000,
    rating: 4.88,
    projectsCompleted: 22,
    verification: {
      toolsVerified: true,
      toolsVerifiedNote: 'Creator submitted generative workflow assets.',
      workflowVerified: true,
      workflowVerifiedNote: 'Comprehensive review of cinematic generation pipeline.',
      pastWorkVerified: false,
    },
    createdAt: '2026-01-13T10:00:00.000Z',
    updatedAt: '2026-01-13T10:00:00.000Z',
  },
  {
    _id: 'creator_4',
    userId: 'user_creator_4',
    name: 'Ananya Sharma',
    location: 'Delhi, NCR',
    headline: 'Gen Z Streetwear, Micro-Trends & Viral TikTok/Reels Video',
    bio: 'Obsessed with the pulse of Delhi youth culture and cyber-aesthetic streetwear. I build ultra-fast, viral, beat-matched 9:16 vertical video drops that capture Gen Z attention in the first 0.5 seconds.',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
    specialization: 'Streetwear & Gen Z',
    skills: ['Vertical Video', 'Fast-Cut Editing', 'Cyber Aesthetic', 'Pop Culture Trendjacking', 'Audio Sync'],
    tools: ['Kling AI', 'Runway Gen-3 Alpha', 'Midjourney v6', 'CapCut Pro', 'Flux.1 Pro'],
    models: ['Kling 1.5', 'Runway Gen-3 Alpha Turbo', 'Flux Schnell'],
    contentTypes: ['Video Ad', 'Social Short', 'Fashion Film', 'Motion Poster'],
    styles: ['Cyberpunk', 'Gen Z / Glitch', 'Retro-Futuristic', 'Vibrant', 'Bold'],
    formats: ['MP4', 'Vertical 1080x1920'],
    supportedAspectRatios: ['9:16', '4:5', '1:1'],
    commercialUseReady: true,
    workflow: [
      'TikTok/Reels sound selection and BPM beat mapping',
      'Flux.1 streetwear textile & sneaker render pass',
      'Kling AI 1.5 hyper-speed kinetic transitions',
      'Mobile-optimized grading with high contrast and punchy saturation',
    ],
    rateFrom: 18000,
    rating: 4.96,
    projectsCompleted: 45,
    verification: {
      toolsVerified: true,
      toolsVerifiedNote: 'Active creator license verified on Kling & Runway.',
      workflowVerified: true,
      workflowVerifiedNote: 'Pacing & video synchronicity verified through production log.',
      pastWorkVerified: true,
      pastWorkVerifiedNote: 'Endorsed by multiple Indian D2C streetwear labels.',
    },
    createdAt: '2026-01-14T10:00:00.000Z',
    updatedAt: '2026-01-14T10:00:00.000Z',
  },
  {
    _id: 'creator_5',
    userId: 'user_creator_5',
    name: 'Arjun Rao',
    location: 'Hyderabad, Telangana',
    headline: 'Sensory Food & Beverage Commercials with Liquid Dynamics',
    bio: 'Crafting mouth-watering, hyper-tactile AI commercials for gourmet FMCG, coffee, and artisanal confectionery brands. High speed pours, steam realism, and macro lens textures.',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
    specialization: 'Food & Beverage',
    skills: ['Liquid Dynamics', 'Macro Food Visuals', 'Sensory Lighting', 'Commercial Ads', 'Color Finishing'],
    tools: ['Midjourney v6', 'Luma Dream Machine', 'Runway Gen-3 Alpha', 'Topaz Video AI'],
    models: ['Midjourney v6.1', 'Luma Ray 2', 'Runway Gen-3 Alpha Turbo'],
    contentTypes: ['Product Commercial', 'Video Ad', 'Social Teaser', 'Sensory Ad'],
    styles: ['Warm & Cozy', 'Hyper-realistic', 'Sensory', 'Artisanal', 'Cinematic'],
    formats: ['MP4', '4K 60fps'],
    supportedAspectRatios: ['1:1', '16:9', '9:16', '4:5'],
    commercialUseReady: true,
    workflow: [
      'Midjourney v6 macro food texture framing with rim-lighting prompts',
      'Luma Ray 2 slow-motion steam, pour, and particle animation',
      'Topaz Video AI 60fps frame interpolation for silky playback',
      'Sound design with real acoustic sizzling, pouring, and crunching textures',
    ],
    rateFrom: 22000,
    rating: 4.89,
    projectsCompleted: 19,
    verification: {
      toolsVerified: true,
      toolsVerifiedNote: 'Verified creator tools setup.',
      workflowVerified: true,
      workflowVerifiedNote: 'Multi-stage food macro simulation workflow verified.',
      pastWorkVerified: true,
      pastWorkVerifiedNote: 'Commercial broadcast assets confirmed for specialty cafe chain.',
    },
    createdAt: '2026-01-15T10:00:00.000Z',
    updatedAt: '2026-01-15T10:00:00.000Z',
  },
  {
    _id: 'creator_6',
    userId: 'user_creator_6',
    name: 'Meera Iyer',
    location: 'Chennai, Tamil Nadu',
    headline: 'Luxury Perfume & Cosmetics Beauty Films',
    bio: 'Creating ethereal, dreamlike fragrance commercials and cosmetic reveals with crystalline water reflections, floral particle explosions, and soft golden-hour diffusion.',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=300&auto=format&fit=crop&q=80',
    specialization: 'Beauty & Luxury',
    skills: ['Beauty Lighting', 'Fluid Aesthetics', 'Reflective Glass Physics', 'Minimal Typography', 'Mood Films'],
    tools: ['Flux.1 Pro', 'Runway Gen-3 Alpha', 'Midjourney v6', 'Magnific AI', 'After Effects'],
    models: ['Flux Schnell', 'Runway Gen-3 Alpha Turbo', 'Midjourney v6.1'],
    contentTypes: ['Product Commercial', 'Fashion Film', 'Brand Film', 'Video Ad'],
    styles: ['Luxury', 'Ethereal', 'Minimalist', 'Pastel / Dreamy', 'Cinematic'],
    formats: ['MP4', 'ProRes'],
    supportedAspectRatios: ['9:16', '1:1', '16:9'],
    commercialUseReady: true,
    workflow: [
      'Flux.1 glass refraction and caustics rendering',
      'Runway Gen-3 Alpha floating botanical particle motion',
      'Magnific AI high-definition cosmetic skin texture enhancement',
      'Spatial ambient score composition and elegant typographic overlay',
    ],
    rateFrom: 30000,
    rating: 4.97,
    projectsCompleted: 31,
    verification: {
      toolsVerified: true,
      toolsVerifiedNote: 'Verified enterprise Flux.1 and Runway accounts.',
      workflowVerified: true,
      workflowVerifiedNote: 'Full documentation of beauty asset workflow accepted.',
      pastWorkVerified: true,
      pastWorkVerifiedNote: 'Endorsed by premium skincare brand in Chennai.',
    },
    createdAt: '2026-01-16T10:00:00.000Z',
    updatedAt: '2026-01-16T10:00:00.000Z',
  },
  {
    _id: 'creator_7',
    userId: 'user_creator_7',
    name: 'Dev Khanna',
    location: 'Pune, Maharashtra',
    headline: 'High-Energy AI Sports & Activewear Cinematic Spots',
    bio: 'Capturing explosive human kinetics, athletic sweat, stadium lights, and dynamic camera swoops for activewear, fitness apps, and cricket gear campaigns.',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300&auto=format&fit=crop&q=80',
    specialization: 'Sports & Kinetics',
    skills: ['Kinetic Camera Motion', 'Anatomy Consistency', 'Stadium Lighting', 'High-Impact Cuts', 'Sports Audio'],
    tools: ['Runway Gen-3 Alpha', 'Kling AI', 'Midjourney v6', 'DaVinci Resolve'],
    models: ['Runway Gen-3 Alpha Turbo', 'Kling 1.5', 'Midjourney v6.1'],
    contentTypes: ['Video Ad', 'Brand Anthem', 'Social Short', 'Teaser'],
    styles: ['High-Energy', 'Cinematic', 'Gritty & Real', 'Dynamic'],
    formats: ['MP4', 'ProRes'],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    commercialUseReady: true,
    workflow: [
      'Athlete pose reference mapping using ControlNet conditioning',
      'Kling AI 1.5 explosive sprint and leap dynamics',
      'Runway Gen-3 Alpha continuous drone tracking zoom',
      'Sound design with heartbeat buildup, breath panting, and roaring crowds',
    ],
    rateFrom: 20000,
    rating: 4.85,
    projectsCompleted: 17,
    verification: {
      toolsVerified: true,
      toolsVerifiedNote: 'Creator verified on Kling and Runway pipelines.',
      workflowVerified: true,
      workflowVerifiedNote: 'Sports kinetic pipeline reviewed.',
      pastWorkVerified: false,
    },
    createdAt: '2026-01-17T10:00:00.000Z',
    updatedAt: '2026-01-17T10:00:00.000Z',
  },
  {
    _id: 'creator_8',
    userId: 'user_creator_8',
    name: 'Ishita Verma',
    location: 'Kolkata, West Bengal',
    headline: 'Cultural Storytelling, Heritage Travel & AI Documentaries',
    bio: 'Weaving poetic heritage visual poetry for tourism boards, luxury resorts, and cultural preservation trusts. Evocative lighting, historical authenticity, and sensory Indian soundscapes.',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
    specialization: 'Travel & Culture',
    skills: ['Cultural Aesthetics', 'Drone Emulation', 'Poetic Narratives', 'Historic Realism', 'Folk Sound Design'],
    tools: ['Midjourney v6', 'Runway Gen-3 Alpha', 'Luma Dream Machine', 'ElevenLabs', 'Premiere Pro'],
    models: ['Midjourney v6.1', 'Runway Gen-3 Alpha Turbo', 'Luma Ray 2', 'ElevenLabs Multilingual v2'],
    contentTypes: ['Brand Film', 'Travel Video', 'Documentary Short', 'Cinematic Teaser'],
    styles: ['Poetic', 'Cinematic', 'Warm & Nostalgic', 'Authentic', 'Vibrant'],
    formats: ['MP4', '4K UHD'],
    supportedAspectRatios: ['16:9', '9:16'],
    commercialUseReady: true,
    workflow: [
      'Historical visual research and architectural motif prompts',
      'Midjourney golden-hour wide panoramic plate generation',
      'Runway Gen-3 Alpha slow poetic push-ins and atmospheric dust motes',
      'ElevenLabs multilingual authentic voiceover narration & sitar drone score',
    ],
    rateFrom: 24000,
    rating: 4.94,
    projectsCompleted: 26,
    verification: {
      toolsVerified: true,
      toolsVerifiedNote: 'Verified creator tools access.',
      workflowVerified: true,
      workflowVerifiedNote: 'Heritage documentary synthesis review completed.',
      pastWorkVerified: true,
      pastWorkVerifiedNote: 'Tourism promotional work verified in Kolkata.',
    },
    createdAt: '2026-01-18T10:00:00.000Z',
    updatedAt: '2026-01-18T10:00:00.000Z',
  },
  {
    _id: 'creator_9',
    userId: 'user_creator_9',
    name: 'Aditya Nair',
    location: 'Bengaluru, Karnataka',
    headline: 'AI Character Animation, Anime & Mascot Design for Tech Brands',
    bio: 'Designing unforgettable generative 2D/3D characters, anime shorts, and interactive brand mascots for gaming studios, fintech apps, and edtech platforms.',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80',
    specialization: 'Character & Animation',
    skills: ['Character Consistency', 'Anime Style Synthesis', 'Lip Sync', 'Expressive Facial Rigging', 'Storyboarding'],
    tools: ['ComfyUI', 'Kling AI', 'Midjourney v6', 'LivePortrait', 'ElevenLabs'],
    models: ['ComfyUI SDXL LoRAs', 'Kling 1.5', 'LivePortrait v1'],
    contentTypes: ['Animation', 'Character Spot', 'Social Short', 'Video Ad'],
    styles: ['Anime / Manga', '3D Stylized', 'Futuristic', 'Playful & Quirky'],
    formats: ['MP4', '60fps'],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    commercialUseReady: true,
    workflow: [
      'Consistent character sheet design with multi-angle turnaround in Midjourney',
      'ComfyUI IP-Adapter conditioning for zero face-drift',
      'LivePortrait facial expression mapping & Kling body movement',
      'ElevenLabs custom voice character performance sync',
    ],
    rateFrom: 26000,
    rating: 4.91,
    projectsCompleted: 23,
    verification: {
      toolsVerified: true,
      toolsVerifiedNote: 'Verified ComfyUI node workflows and LoRA training scripts.',
      workflowVerified: true,
      workflowVerifiedNote: 'Character turnaround consistency verified.',
      pastWorkVerified: true,
      pastWorkVerifiedNote: 'Fintech client mascot animation confirmed.',
    },
    createdAt: '2026-01-19T10:00:00.000Z',
    updatedAt: '2026-01-19T10:00:00.000Z',
  },
  {
    _id: 'creator_10',
    userId: 'user_creator_10',
    name: 'Sara Bansal',
    location: 'Mumbai, Maharashtra',
    headline: 'Architectural AI Cinema & Spatial Real Estate Visualizations',
    bio: 'Transforming blueprints and speculative luxury developments into immersive hyper-realistic walkthroughs and dusk-to-dawn cinematic films for prime real estate developers.',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=300&auto=format&fit=crop&q=80',
    specialization: 'Architecture & Spaces',
    skills: ['Spatial AI Visualization', 'Interior Lighting Physics', 'Drone Flythroughs', 'Material Realism', 'Architectural Storytelling'],
    tools: ['Flux.1 Pro', 'Runway Gen-3 Alpha', 'Luma Dream Machine', 'Magnific AI', 'Cinema 4D'],
    models: ['Flux Schnell', 'Runway Gen-3 Alpha Turbo', 'Luma Ray 2'],
    contentTypes: ['Brand Film', 'Virtual Walkthrough', 'Product Commercial', 'Teaser'],
    styles: ['Architectural', 'Luxury', 'Minimalist', 'Hyper-realistic', 'Cinematic'],
    formats: ['MP4', '4K UHD'],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    commercialUseReady: true,
    workflow: [
      'Flux.1 Pro photorealistic interior material & natural sunlighting renders',
      'Luma Ray 2 continuous smooth camera glide through architectural spaces',
      'Magnific AI structural line sharpening and marble/wood micro-textures',
      'Soundscape of ocean breeze, subtle footsteps, and ambient acoustics',
    ],
    rateFrom: 35000,
    rating: 4.98,
    projectsCompleted: 29,
    verification: {
      toolsVerified: true,
      toolsVerifiedNote: 'Architectural pipeline verified with CAD to Flux workflow.',
      workflowVerified: true,
      workflowVerifiedNote: 'Spatial continuity workflow verified by architecture advisor.',
      pastWorkVerified: true,
      pastWorkVerifiedNote: 'Completed luxury penthouse launch film in South Mumbai.',
    },
    createdAt: '2026-01-20T10:00:00.000Z',
    updatedAt: '2026-01-20T10:00:00.000Z',
  },
];

// 22 realistic portfolio items with at least 10 real browser-playable HTML5 MP4 videos
export const SEED_PORTFOLIO: PortfolioItem[] = [
  // 1. Aarav Mehta (Fashion) - REAL PLAYABLE VIDEO (9:16 vertical)
  {
    _id: 'port_1_video',
    creatorId: 'creator_1',
    title: 'AI Fashion Campaign — Editorial Vertical Film',
    description: 'AI-generated fashion campaign film focused on premium clothing visuals, cinematic movement, and vertical social-first presentation.',
    contentType: 'Fashion Campaign',
    assetType: 'video',
    assetUrl: '/videos/video-2-fashion.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=80',
    toolsUsed: ['AI Video Generation'],
    modelsUsed: [],
    workflow: [
      'AI-generated fashion concept and visual direction',
      'Cinematic motion and vertical campaign composition',
      'Social-first fashion presentation',
    ],
    aspectRatio: '9:16',
    styles: ['Luxury', 'Cinematic', 'Futuristic'],
    commercialUse: true,
    tags: ['Fashion', 'Vertical Video', 'Luxury', 'Fashion Campaign', 'AI Video'],
    createdAt: '2026-01-22T10:00:00.000Z',
    updatedAt: '2026-01-22T10:00:00.000Z',
  },
  // 2. Aarav Mehta - REAL PLAYABLE VIDEO (16:9 cinematic)
  {
    _id: 'port_2_video',
    creatorId: 'creator_1',
    title: 'Future Phone — Premium Smartphone Commercial',
    description: 'AI-generated premium smartphone commercial featuring a futuristic device, cinematic product shots, polished lighting, and a high-end technology advertising aesthetic.',
    contentType: 'Product Commercial',
    assetType: 'video',
    assetUrl: '/videos/video-1-smartphone.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop&q=80',
    toolsUsed: ['Google Gemini'],
    modelsUsed: [],
    workflow: [
      'Google Gemini AI video generation',
      'Futuristic product visual direction',
      'Cinematic smartphone commercial composition',
    ],
    aspectRatio: '16:9',
    styles: ['Cinematic', 'Premium', 'Futuristic'],
    commercialUse: true,
    tags: ['Smartphone', 'Product Commercial', 'Cinematic', 'Futuristic', 'Technology'],
    createdAt: '2026-01-23T10:00:00.000Z',
    updatedAt: '2026-01-23T10:00:00.000Z',
  },
  // 3. Aarav Mehta - Image
  {
    _id: 'port_3_image',
    creatorId: 'creator_1',
    title: 'Cyber Banarasi — Heritage Meets 2077 Editorial',
    description: 'Vogue-style high fashion editorial combining traditional Varanasi zari weaves with cybernetic metallic accents.',
    contentType: 'Fashion Editorial',
    assetType: 'image',
    assetUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=1200&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&auto=format&fit=crop&q=80',
    toolsUsed: ['Midjourney v6', 'Magnific AI'],
    modelsUsed: ['Midjourney v6.1'],
    workflow: ['Midjourney v6 prompt chain with exact textile weighting', 'Magnific AI 8K thread detail pass'],
    aspectRatio: '4:5',
    styles: ['Luxury', 'Futuristic'],
    commercialUse: true,
    tags: ['Fashion', 'Editorial', 'Heritage', 'Textile'],
    createdAt: '2026-01-24T10:00:00.000Z',
    updatedAt: '2026-01-24T10:00:00.000Z',
  },

  // 4. Riya Kapoor (EV Commercial) - REAL PLAYABLE VIDEO (16:9)
  {
    _id: 'port_4_video',
    creatorId: 'creator_2',
    title: 'Coastal Drive — Automotive Lifestyle Commercial',
    description: 'Cinematic automotive lifestyle film following a premium car along a dramatic coastal road with aerial driving imagery and ocean scenery.',
    contentType: 'Video Ad',
    assetType: 'video',
    assetUrl: '/videos/video-5-automotive-drive.mp4',
    thumbnailUrl: '/videos/video-5-automotive-drive.jpg',
    toolsUsed: ['AI Video Generation'],
    modelsUsed: [],
    workflow: ['Cinematic automotive footage', 'Aerial driving composition and environmental storytelling'],
    aspectRatio: '9:16',
    styles: ['Cinematic', 'Automotive', 'Lifestyle'],
    commercialUse: true,
    tags: ['Automotive', 'Car Commercial', 'Coastal', 'Lifestyle'],
    createdAt: '2026-01-25T10:00:00.000Z',
    updatedAt: '2026-01-25T10:00:00.000Z',
  },
  // 5. Riya Kapoor - REAL PLAYABLE VIDEO (9:16 vertical)
  {
_id: 'port_5_video',
    creatorId: 'creator_2',
    title: 'Autonomous Urban Commute — Mobile Story Ad',
    description: 'Vertical social ad showcasing smart cockpit interaction and urban neon reflection gliding through nocturnal cityscape.',
    contentType: 'Product Commercial',
    assetType: 'image',
    assetUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop&q=80',
    toolsUsed: ['Luma Dream Machine', 'Runway Gen-3 Alpha', 'ElevenLabs'],
    modelsUsed: ['Luma Ray 2', 'Runway Gen-3 Alpha Turbo'],
    workflow: [
      'Luma Ray 2 interior cockpit camera pan',
      'Runway Gen-3 exterior neon blur integration',
      'ElevenLabs UI chime sound effects',
    ],
    aspectRatio: '9:16',
    styles: ['Tech-Forward', 'Futuristic'],
    commercialUse: true,
    tags: ['Automotive', 'Tech', 'Vertical Ad', 'UI'],
    createdAt: '2026-01-26T10:00:00.000Z',
    updatedAt: '2026-01-26T10:00:00.000Z',
  },

  // 6. Kabir Malhotra (Cinematic VFX) - REAL PLAYABLE VIDEO (16:9)
  {
    _id: 'port_6_video',
    creatorId: 'creator_3',
    title: 'Velocity After Dark — Formula One Cinematic Performance Film',
    description: 'Cinematic motorsport performance film featuring a Formula One-style race car in a dramatic studio environment with premium lighting and reflections.',
    contentType: 'Brand Film',
    assetType: 'video',
    assetUrl: '/videos/video-3-formula1-cinematic.mp4',
    thumbnailUrl: '/videos/video-3-formula1-cinematic.jpg',
    toolsUsed: ['AI Video Generation'],
    modelsUsed: [],
    workflow: ['AI-generated cinematic automotive imagery', 'Cinematic lighting and motion treatment'],
    aspectRatio: '9:16',
    styles: ['Cinematic', 'Futuristic', 'High-Octane'],
    commercialUse: true,
    tags: ['Automotive', 'Formula One', 'Cinematic', 'Brand Film'],
    createdAt: '2026-01-27T10:00:00.000Z',
    updatedAt: '2026-01-27T10:00:00.000Z',
  },
  // 7. Kabir Malhotra - Image
  {
    _id: 'port_7_image',
    creatorId: 'creator_3',
    title: 'Neo-Varanasi 2099 — Sacred Ghats of the Solar Age',
    description: 'High-concept architectural worldbuilding integrating ancient river stone steps with floating holographic lotus lanterns.',
    contentType: 'Concept Art',
    assetType: 'image',
    assetUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    toolsUsed: ['Flux.1 Pro', 'Magnific AI'],
    modelsUsed: ['Flux Schnell'],
    workflow: ['Flux.1 Pro architectural prompt engineering', 'Magnific AI structure enhance'],
    aspectRatio: '16:9',
    styles: ['Futuristic', 'Atmospheric'],
    commercialUse: true,
    tags: ['Architecture', 'Worldbuilding', 'India', 'Concept Art'],
    createdAt: '2026-01-28T10:00:00.000Z',
    updatedAt: '2026-01-28T10:00:00.000Z',
  },

  // 8. Ananya Sharma (Gen Z / Streetwear) - REAL PLAYABLE VIDEO (9:16 vertical)
  {
    _id: 'port_8_video',
    creatorId: 'creator_4',
    title: 'Gully Glitch — Gen Z Cyber Sneaker Drop',
    description: 'Hyper-kinetic vertical promo for a limited sneaker drop. 140 BPM beat sync with glowing soles, chrome laces, and lightning-fast snap transitions.',
    contentType: 'Video Ad',
    assetType: 'image',
    assetUrl: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&auto=format&fit=crop&q=80',
    toolsUsed: ['Kling AI', 'Runway Gen-3 Alpha', 'CapCut Pro'],
    modelsUsed: ['Kling 1.5', 'Runway Gen-3 Alpha Turbo'],
    workflow: [
      'Kling AI 1.5 rapid sneaker 360 spin animation',
      'CapCut rhythm-locked speed ramps',
      'Subtle RGB glitch chromatic aberration overlay',
    ],
    aspectRatio: '9:16',
    styles: ['Gen Z / Glitch', 'Cyberpunk', 'Vibrant'],
    commercialUse: true,
    tags: ['Streetwear', 'Sneakers', 'Vertical Video', 'Gen Z', 'Viral'],
    createdAt: '2026-01-29T10:00:00.000Z',
    updatedAt: '2026-01-29T10:00:00.000Z',
  },
  // 9. Ananya Sharma - REAL PLAYABLE VIDEO (1:1 square)
  {
    _id: 'port_9_video',
    creatorId: 'creator_4',
    title: 'MonoForm — Premium Headphones Product Visualization',
    description: 'Minimalist product visualization of premium wireless headphones with a clean studio aesthetic and dramatic silhouette lighting.',
    contentType: 'Product Commercial',
    assetType: 'video',
    assetUrl: '/videos/video-4-headphones-product.mp4',
    thumbnailUrl: '/videos/video-4-headphones-product.jpg',
    toolsUsed: ['AI Video Generation'],
    modelsUsed: [],
    workflow: ['AI-generated product visualization', 'Studio lighting and motion treatment'],
    aspectRatio: '4:5',
    styles: ['Minimalist', 'Premium', 'Product Visualization'],
    commercialUse: true,
    tags: ['Headphones', 'Product', '3D', 'Motion Graphics', 'Product Commercial'],
    createdAt: '2026-01-30T10:00:00.000Z',
    updatedAt: '2026-01-30T10:00:00.000Z',
  },

  // 10. Arjun Rao (Food & Beverage) - REAL PLAYABLE VIDEO (1:1 square)
  {
_id: 'port_10_video',
    creatorId: 'creator_5',
    title: 'Monsoon Espresso — The Velvet Pour',
    description: 'Sensory macro coffee commercial showing dark espresso crema swirling into cold whole milk. Extreme slow motion fluid dynamics with crystal clear acoustics.',
    contentType: 'Product Commercial',
    assetType: 'image',
    assetUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
    toolsUsed: ['Luma Dream Machine', 'Midjourney v6', 'Topaz Video AI'],
    modelsUsed: ['Luma Ray 2', 'Midjourney v6.1'],
    workflow: [
      'Midjourney v6 macro lighting and glass texture prompts',
      'Luma Ray 2 fluid curl vortex generation',
      'Topaz 60fps frame interpolation & sound design',
    ],
    aspectRatio: '1:1',
    styles: ['Sensory', 'Artisanal', 'Hyper-realistic'],
    commercialUse: true,
    tags: ['Coffee', 'Food & Beverage', 'Sensory', 'Macro'],
    createdAt: '2026-01-31T10:00:00.000Z',
    updatedAt: '2026-01-31T10:00:00.000Z',
  },
  // 11. Arjun Rao - Image
  {
    _id: 'port_11_image',
    creatorId: 'creator_5',
    title: 'Golden Saffron Brioche — Crust & Steam Macro',
    description: 'High-detail food magazine photography capturing freshly torn buttery bread with rising delicate steam and sea salt flecks.',
    contentType: 'Product Photography',
    assetType: 'image',
    assetUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1200&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80',
    toolsUsed: ['Midjourney v6', 'Magnific AI'],
    modelsUsed: ['Midjourney v6.1'],
    workflow: ['Midjourney v6 macro lens and golden hour lighting', 'Magnific AI crust sharpness'],
    aspectRatio: '4:5',
    styles: ['Artisanal', 'Warm & Cozy'],
    commercialUse: true,
    tags: ['Food', 'Bakery', 'Artisanal', 'Macro'],
    createdAt: '2026-02-01T10:00:00.000Z',
    updatedAt: '2026-02-01T10:00:00.000Z',
  },

  // 12. Meera Iyer (Beauty & Luxury) - REAL PLAYABLE VIDEO (9:16 vertical)
  {
    _id: 'port_12_video',
    creatorId: 'creator_6',
    title: 'Hydra Lumière — Serum Drop Reflection Film',
    description: 'High-end beauty serum commercial featuring a suspended droplet touching water ripples with blooming jasmine petals in soft daylight.',
    contentType: 'Product Commercial',
    assetType: 'image',
    assetUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=80',
    toolsUsed: ['Flux.1 Pro', 'Runway Gen-3 Alpha', 'Magnific AI'],
    modelsUsed: ['Flux Schnell', 'Runway Gen-3 Alpha Turbo'],
    workflow: [
      'Flux.1 caustics and cosmetic fluid physics styling',
      'Runway Gen-3 Alpha gentle ripple wave propagation',
      'Magnific AI droplet clarity restoration',
    ],
    aspectRatio: '9:16',
    styles: ['Luxury', 'Ethereal', 'Minimalist'],
    commercialUse: true,
    tags: ['Beauty', 'Skincare', 'Serum', 'Luxury', 'Ethereal'],
    createdAt: '2026-02-02T10:00:00.000Z',
    updatedAt: '2026-02-02T10:00:00.000Z',
  },
  // 13. Meera Iyer - Image
  {
    _id: 'port_13_image',
    creatorId: 'creator_6',
    title: 'Oud & Rose — Sculptural Glass Perfume Flacon',
    description: 'Clean architectural product shot of a faceted crystal fragrance bottle with morning sunlight casting tinted shadows.',
    contentType: 'Product Photography',
    assetType: 'image',
    assetUrl: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=1200&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&auto=format&fit=crop&q=80',
    toolsUsed: ['Flux.1 Pro', 'Midjourney v6'],
    modelsUsed: ['Flux Schnell', 'Midjourney v6.1'],
    workflow: ['Flux.1 Pro glass refraction prompts', 'Midjourney tonal color correction'],
    aspectRatio: '1:1',
    styles: ['Luxury', 'Minimalist'],
    commercialUse: true,
    tags: ['Perfume', 'Luxury', 'Product Shot', 'Minimalism'],
    createdAt: '2026-02-03T10:00:00.000Z',
    updatedAt: '2026-02-03T10:00:00.000Z',
  },

  // 14. Dev Khanna (Sports & Kinetics) - REAL PLAYABLE VIDEO (16:9)
  {
    _id: 'port_14_video',
    creatorId: 'creator_7',
    title: 'The Final Over — Night Cricket Anthem',
    description: 'High-octane sports anthem capturing a fast bowler running in under roaring floodlights with dirt spray and seam spin.',
    contentType: 'Video Ad',
    assetType: 'image',
    assetUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&auto=format&fit=crop&q=80',
    toolsUsed: ['Kling AI', 'Runway Gen-3 Alpha', 'DaVinci Resolve'],
    modelsUsed: ['Kling 1.5', 'Runway Gen-3 Alpha Turbo'],
    workflow: [
      'ControlNet skeleton reference for fast bowler stride',
      'Kling AI 1.5 velocity burst and stadium crowd blur',
      'DaVinci Resolve explosive dynamic range grading',
    ],
    aspectRatio: '16:9',
    styles: ['High-Energy', 'Cinematic', 'Dynamic'],
    commercialUse: true,
    tags: ['Sports', 'Cricket', 'High Energy', 'Stadium'],
    createdAt: '2026-02-04T10:00:00.000Z',
    updatedAt: '2026-02-04T10:00:00.000Z',
  },

  // 15. Ishita Verma (Culture & Travel) - REAL PLAYABLE VIDEO (16:9)
  {
    _id: 'port_15_video',
    creatorId: 'creator_8',
    title: 'Ladakh: The Silent Pass — Tourism Film',
    description: 'Poetic travel documentary across high-altitude Himalayan passes. Monasteries clinging to cliffs, prayer flags snapping in crisp wind, and golden mountain peaks.',
    contentType: 'Travel Video',
    assetType: 'image',
    assetUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80',
    toolsUsed: ['Runway Gen-3 Alpha', 'Midjourney v6', 'ElevenLabs'],
    modelsUsed: ['Runway Gen-3 Alpha Turbo', 'Midjourney v6.1', 'ElevenLabs Multilingual v2'],
    workflow: [
      'Midjourney v6 Himalayan aerial landscape synthesis',
      'Runway Gen-3 Alpha cinematic drone pull-back motion',
      'ElevenLabs ambient Tibetan horn and wind sound design',
    ],
    aspectRatio: '16:9',
    styles: ['Poetic', 'Cinematic', 'Authentic'],
    commercialUse: true,
    tags: ['Travel', 'Ladakh', 'Himalayas', 'Documentary', 'Poetic'],
    createdAt: '2026-02-05T10:00:00.000Z',
    updatedAt: '2026-02-05T10:00:00.000Z',
  },
  // 16. Ishita Verma - Image
  {
    _id: 'port_16_image',
    creatorId: 'creator_8',
    title: 'Dawn on Dal Lake — Shikara Mist',
    description: 'Atmospheric morning light filtering through autumn chinars onto still waters of Kashmir with water lilies and wooden boats.',
    contentType: 'Travel Photography',
    assetType: 'image',
    assetUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
    toolsUsed: ['Midjourney v6', 'Flux.1 Pro'],
    modelsUsed: ['Midjourney v6.1', 'Flux Schnell'],
    workflow: ['Midjourney v6 mist layering', 'Flux.1 water reflection accuracy'],
    aspectRatio: '16:9',
    styles: ['Poetic', 'Atmospheric'],
    commercialUse: true,
    tags: ['Travel', 'Kashmir', 'Heritage', 'Nature'],
    createdAt: '2026-02-06T10:00:00.000Z',
    updatedAt: '2026-02-06T10:00:00.000Z',
  },

  // 17. Aditya Nair (Character & Animation) - REAL PLAYABLE VIDEO (16:9)
  {
    _id: 'port_17_video',
    creatorId: 'creator_9',
    title: 'Byte & Bolt — Fintech AI Companion Intro',
    description: '3D stylized animation short introducing a playful electric fox mascot explaining smart savings for a neo-banking app.',
    contentType: 'Animation',
    assetType: 'image',
    assetUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80',
    toolsUsed: ['ComfyUI', 'Kling AI', 'LivePortrait', 'ElevenLabs'],
    modelsUsed: ['ComfyUI SDXL LoRAs', 'Kling 1.5'],
    workflow: [
      'LoRA trained specifically on client brand mascot geometry',
      'LivePortrait keyframe facial expression synchronicity',
      'Kling AI 1.5 playful jumping and tail wag physics',
    ],
    aspectRatio: '16:9',
    styles: ['3D Stylized', 'Playful & Quirky'],
    commercialUse: true,
    tags: ['Animation', 'Mascot', 'Fintech', 'Character Design'],
    createdAt: '2026-02-07T10:00:00.000Z',
    updatedAt: '2026-02-07T10:00:00.000Z',
  },
  // 18. Aditya Nair - Image
  {
    _id: 'port_18_image',
    creatorId: 'creator_9',
    title: 'Cyber Ronin: Neo Bangalore — Anime Key Visual',
    description: 'Studio Ghibli meets Akira aesthetic key visual of a cybernetic warrior resting near an electric tea stall under purple monsoon rain.',
    contentType: 'Anime Key Visual',
    assetType: 'image',
    assetUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1200&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
    toolsUsed: ['Midjourney v6', 'ComfyUI'],
    modelsUsed: ['Midjourney v6.1'],
    workflow: ['Midjourney anime watercolor prompt style', 'ComfyUI lineart enhancement'],
    aspectRatio: '16:9',
    styles: ['Anime / Manga', 'Futuristic'],
    commercialUse: true,
    tags: ['Anime', 'Illustration', 'Cyberpunk', 'Art'],
    createdAt: '2026-02-08T10:00:00.000Z',
    updatedAt: '2026-02-08T10:00:00.000Z',
  },

  // 19. Sara Bansal (Architecture & Spaces) - REAL PLAYABLE VIDEO (16:9)
  {
    _id: 'port_19_video',
    creatorId: 'creator_10',
    title: 'The Sky Villa — Dusk Architectural Walkthrough',
    description: 'Hyper-realistic architectural film gliding through an infinity pool terrace overlooking Mumbai skyline at twilight. Ambient sea breeze and warm limestone textures.',
    contentType: 'Brand Film',
    assetType: 'image',
    assetUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    toolsUsed: ['Flux.1 Pro', 'Runway Gen-3 Alpha', 'Magnific AI'],
    modelsUsed: ['Flux Schnell', 'Runway Gen-3 Alpha Turbo'],
    workflow: [
      'Flux.1 Pro lighting and stone texture generation',
      'Runway Gen-3 steady camera track forward',
      'Magnific AI structural clean lines enhancement',
    ],
    aspectRatio: '16:9',
    styles: ['Architectural', 'Luxury', 'Hyper-realistic'],
    commercialUse: true,
    tags: ['Architecture', 'Real Estate', 'Luxury', 'Interior'],
    createdAt: '2026-02-09T10:00:00.000Z',
    updatedAt: '2026-02-09T10:00:00.000Z',
  },
  // 20. Sara Bansal - Image
  {
    _id: 'port_20_image',
    creatorId: 'creator_10',
    title: 'Courtyard of Shadows — Brutalist Stone Pavilion',
    description: 'Photorealistic architectural render of a minimalist concrete and teak pavilion with dappled tropical palm shadows.',
    contentType: 'Architectural Render',
    assetType: 'image',
    assetUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&auto=format&fit=crop&q=80',
    toolsUsed: ['Flux.1 Pro', 'Magnific AI'],
    modelsUsed: ['Flux Schnell'],
    workflow: ['Flux.1 concrete shadow diffusion prompts', 'Magnific architectural line sharpness'],
    aspectRatio: '16:9',
    styles: ['Architectural', 'Minimalist'],
    commercialUse: true,
    tags: ['Architecture', 'Minimalism', 'Interior Design'],
    createdAt: '2026-02-10T10:00:00.000Z',
    updatedAt: '2026-02-10T10:00:00.000Z',
  },
  // 21. Additional Video (Fashion 9:16) for Creator 1
  {
    _id: 'port_21_video',
    creatorId: 'creator_1',
    title: 'Aura of Jaipur — Futuristic Royal Wedding Spec',
    description: 'Spectacular 9:16 mobile ad blending royal Rajasthani lehengas with kinetic holographic gold thread reflections for modern festive campaigns.',
    contentType: 'Fashion Film',
    assetType: 'image',
    assetUrl: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80',
    toolsUsed: ['Runway Gen-3 Alpha', 'Midjourney v6', 'Flux.1 Pro'],
    modelsUsed: ['Runway Gen-3 Alpha Turbo', 'Midjourney v6.1'],
    workflow: [
      'Midjourney v6 zardozi gold embroidery style lock',
      'Runway Gen-3 Alpha slow vertical camera tilt',
      'Sound design with traditional shehnai and modern 808 bass',
    ],
    aspectRatio: '9:16',
    styles: ['Luxury', 'Cinematic', 'Hyper-realistic'],
    commercialUse: true,
    tags: ['Fashion', 'Wedding', 'Festive', 'Gold', 'Vertical'],
    createdAt: '2026-02-11T10:00:00.000Z',
    updatedAt: '2026-02-11T10:00:00.000Z',
  },
  // 22. Additional Image for Creator 4 (Gen Z Streetwear)
  {
    _id: 'port_22_image',
    creatorId: 'creator_4',
    title: 'Holographic Cyber Kurta — D2C Drop Poster',
    description: 'Bold promotional poster combining neon typography and hyper-detailed iridescent synthetic textiles for youth festival season.',
    contentType: 'Graphic / Poster',
    assetType: 'image',
    assetUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=1200&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=80',
    toolsUsed: ['Midjourney v6', 'Photoshop'],
    modelsUsed: ['Midjourney v6.1'],
    workflow: ['Midjourney textile prompt iteration', 'Photoshop typography layout'],
    aspectRatio: '4:5',
    styles: ['Gen Z / Glitch', 'Cyberpunk', 'Bold'],
    commercialUse: true,
    tags: ['Streetwear', 'Poster', 'Cyberpunk'],
    createdAt: '2026-02-12T10:00:00.000Z',
    updatedAt: '2026-02-12T10:00:00.000Z',
  },
];

export const SEED_BRIEFS: Brief[] = [
  {
    _id: 'brief_1',
    brandId: 'user_brand_demo',
    brandName: 'Zara Modern Luxe India',
    title: 'Festive High-Fashion Reel — Futuristic Urban Luxe',
    description: 'We require a 30-second premium vertical video advertisement for Instagram and YouTube Shorts. Must combine high-end contemporary festive couture with subtle holographic gold particle elements. Clean cloth physics and temporal consistency are paramount.',
    contentType: 'Fashion Film',
    styles: ['Luxury', 'Cinematic', 'Futuristic'],
    aspectRatio: '9:16',
    platform: 'Instagram',
    commercialUse: true,
    commercialUseDetails: {
      territory: 'India & South Asia',
      usageTerm: '12 Months Digital Rights',
      exclusivity: 'Category Exclusive (Apparel)',
      outputOwnership: 'Full Master Asset Buyout with Source Prompts',
    },
    preferredTools: ['Runway Gen-3 Alpha', 'Midjourney v6', 'Flux.1 Pro'],
    creatorRequirements: [
      'Proven portfolio in AI fashion or luxury commercial video',
      'Demonstrated 9:16 vertical video capability with zero face distortion',
      'Delivery of high-bitrate MP4 with master color grade',
    ],
    budget: 35000,
    deadline: '2026-11-15',
    revisionRounds: 2,
    status: 'active',
    createdAt: '2026-02-10T10:00:00.000Z',
    updatedAt: '2026-02-10T10:00:00.000Z',
  },
  {
    _id: 'brief_2',
    brandId: 'user_brand_demo',
    brandName: 'VoltMobility India',
    title: 'Next-Gen EV Commercial — Aerodynamic Velocity',
    description: 'Widescreen 16:9 brand anthem for our new electric performance sedan launch. Needs dramatic dusk lighting, sharp aerodynamic velocity simulations, and cutting-edge visual dynamism.',
    contentType: 'Video Ad',
    styles: ['Futuristic', 'Cinematic', 'High-Octane'],
    aspectRatio: '16:9',
    platform: 'YouTube & Digital OOH',
    commercialUse: true,
    commercialUseDetails: {
      territory: 'Pan India',
      usageTerm: 'In Perpetuity Digital',
      exclusivity: 'Automotive Exclusive',
      outputOwnership: 'Full Commercial Buyout',
    },
    preferredTools: ['Runway Gen-3 Alpha', 'ComfyUI', 'Luma Dream Machine'],
    creatorRequirements: [
      'Automotive consistency experience',
      '4K 60fps export capability',
      'Custom sound design included',
    ],
    budget: 50000,
    deadline: '2026-11-20',
    revisionRounds: 3,
    status: 'active',
    createdAt: '2026-02-12T10:00:00.000Z',
    updatedAt: '2026-02-12T10:00:00.000Z',
  },
  {
    _id: 'brief_3',
    brandId: 'user_brand_demo',
    brandName: 'Third Wave Roast Co.',
    title: 'Artisanal Coffee Brand Film — Sensory Textures',
    description: 'Tactile 1:1 square macro video campaign highlighting slow-drip single origin brews, rising aromatic steam, and velvety crema textures for coffee lovers.',
    contentType: 'Product Commercial',
    styles: ['Sensory', 'Artisanal', 'Warm & Cozy'],
    aspectRatio: '1:1',
    platform: 'Instagram Feed',
    commercialUse: true,
    commercialUseDetails: {
      territory: 'Worldwide Digital',
      usageTerm: '24 Months',
      exclusivity: 'Non-Exclusive',
      outputOwnership: 'Brand License',
    },
    preferredTools: ['Luma Dream Machine', 'Midjourney v6'],
    creatorRequirements: [
      'Fluid physics simulation mastery',
      'Warm aesthetic mastery',
    ],
    budget: 25000,
    deadline: '2026-11-25',
    revisionRounds: 2,
    status: 'active',
    createdAt: '2026-02-14T10:00:00.000Z',
    updatedAt: '2026-02-14T10:00:00.000Z',
  },
  {
    _id: 'brief_4',
    brandId: 'user_brand_demo',
    brandName: 'NeoStreet Athletics',
    title: 'Futuristic Cyber Streetwear — Mumbai 2050',
    description: 'Fast-paced 9:16 mobile drop teaser featuring kinetic model cuts wearing reflective metallic techwear in rainy Mumbai backstreets.',
    contentType: 'Video Ad',
    styles: ['Cyberpunk', 'Gen Z / Glitch', 'Bold'],
    aspectRatio: '9:16',
    platform: 'Instagram Reels & Ads',
    commercialUse: true,
    commercialUseDetails: {
      territory: 'India',
      usageTerm: '6 Months',
      exclusivity: 'Non-Exclusive',
      outputOwnership: 'Digital Social License',
    },
    preferredTools: ['Kling AI', 'Runway Gen-3 Alpha'],
    creatorRequirements: [
      'Experience in viral short-form pacing',
      'Streetwear portfolio sample required',
    ],
    budget: 22000,
    deadline: '2026-12-01',
    revisionRounds: 1,
    status: 'draft',
    createdAt: '2026-02-16T10:00:00.000Z',
    updatedAt: '2026-02-16T10:00:00.000Z',
  },
];

export const SEED_ENGAGEMENTS: Engagement[] = [
  {
    _id: 'eng_1',
    briefId: 'brief_1',
    briefTitle: 'Festive High-Fashion Reel — Futuristic Urban Luxe',
    brandId: 'user_brand_demo',
    brandName: 'Zara Modern Luxe India',
    creatorId: 'creator_1',
    creatorName: 'Aarav Mehta',
    creatorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    stage: 'in_production',
    budget: 35000,
    agreedDeadline: '2026-11-15',
    revisionCount: 0,
    maxRevisions: 2,
    proposalDetails: {
      pitch: 'I will synthesize a 3-act sequence: Act 1 textile macro reveal, Act 2 volumetric runway stride, Act 3 branded logo crest freeze. Will use Runway Gen-3 Alpha with custom camera paths.',
      proposedTimeline: '5 business days for first cut, 2 days for final color conform',
      customRate: 35000,
    },
    deliverables: {
      assetUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
      assetType: 'video',
      submissionNotes: 'Work in progress: First rough cut rendered with temporary ambient score.',
      submittedAt: '2026-02-15T14:30:00.000Z',
    },
    timeline: [
      {
        stage: 'invited',
        timestamp: '2026-02-11T11:00:00.000Z',
        actor: 'Zara Modern Luxe India (Brand)',
        note: 'Invited creator based on 94% matching score on AI fashion video brief.',
      },
      {
        stage: 'proposal',
        timestamp: '2026-02-12T15:20:00.000Z',
        actor: 'Aarav Mehta (Creator)',
        note: 'Submitted 3-act production plan and accepted ₹35,000 milestone.',
      },
      {
        stage: 'in_production',
        timestamp: '2026-02-13T09:00:00.000Z',
        actor: 'Zara Modern Luxe India (Brand)',
        note: 'Proposal accepted. Production initiated.',
      },
    ],
    createdAt: '2026-02-11T11:00:00.000Z',
    updatedAt: '2026-02-15T14:30:00.000Z',
  },
  {
    _id: 'eng_2',
    briefId: 'brief_2',
    briefTitle: 'Next-Gen EV Commercial — Aerodynamic Velocity',
    brandId: 'user_brand_demo',
    brandName: 'VoltMobility India',
    creatorId: 'creator_2',
    creatorName: 'Riya Kapoor',
    creatorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    stage: 'review',
    budget: 50000,
    agreedDeadline: '2026-11-20',
    revisionCount: 1,
    maxRevisions: 3,
    proposalDetails: {
      pitch: 'Deploying ComfyUI for 3D vehicle silhouette preservation paired with Runway Gen-3 4K rolling shutter synthesis.',
      proposedTimeline: '6 business days for complete 4K master',
      customRate: 50000,
    },
    deliverables: {
      assetUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
      assetType: 'video',
      submissionNotes: 'Full 4K commercial export ready for client review. Implemented requested lighting adjustments on rim lights.',
      submittedAt: '2026-02-17T18:00:00.000Z',
    },
    timeline: [
      {
        stage: 'invited',
        timestamp: '2026-02-12T14:00:00.000Z',
        actor: 'VoltMobility India (Brand)',
        note: 'Direct invitation issued.',
      },
      {
        stage: 'proposal',
        timestamp: '2026-02-13T10:15:00.000Z',
        actor: 'Riya Kapoor (Creator)',
        note: 'Production roadmap submitted.',
      },
      {
        stage: 'in_production',
        timestamp: '2026-02-13T16:00:00.000Z',
        actor: 'VoltMobility India (Brand)',
        note: 'Production approved.',
      },
      {
        stage: 'review',
        timestamp: '2026-02-17T18:00:00.000Z',
        actor: 'Riya Kapoor (Creator)',
        note: 'First master cut submitted for review.',
      },
    ],
    createdAt: '2026-02-12T14:00:00.000Z',
    updatedAt: '2026-02-17T18:00:00.000Z',
  },
  {
    _id: 'eng_3',
    briefId: 'brief_3',
    briefTitle: 'Artisanal Coffee Brand Film — Sensory Textures',
    brandId: 'user_brand_demo',
    brandName: 'Third Wave Roast Co.',
    creatorId: 'creator_5',
    creatorName: 'Arjun Rao',
    creatorAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
    stage: 'invited',
    budget: 25000,
    agreedDeadline: '2026-11-25',
    revisionCount: 0,
    maxRevisions: 2,
    timeline: [
      {
        stage: 'invited',
        timestamp: '2026-02-14T12:00:00.000Z',
        actor: 'Third Wave Roast Co. (Brand)',
        note: 'Invited creator based on macro coffee fluid dynamics portfolio.',
      },
    ],
    createdAt: '2026-02-14T12:00:00.000Z',
    updatedAt: '2026-02-14T12:00:00.000Z',
  },
];
